import { MigrationInterface, QueryRunner } from 'typeorm'

const DEFAULT_DASHBOARD_CONFIG = JSON.stringify({
  widgets: [
    'totalLeads',
    'hotLeads',
    'pendingInterviews',
    'activeCases',
    'pendingDocuments',
    'outstandingAmount',
  ],
})

export class CreateLegalBackoffice1784678400000 implements MigrationInterface {
  name = 'CreateLegalBackoffice1784678400000'

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('CREATE SCHEMA IF NOT EXISTS "bo"')

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "bo"."companies" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "name" varchar(255) NOT NULL,
        "theme" varchar(50) NOT NULL DEFAULT 'default',
        "logomarca" bytea,
        "logomarca_mime_type" varchar(30),
        "whatsapp_number" varchar(40),
        "dashboard_config" jsonb NOT NULL DEFAULT '${DEFAULT_DASHBOARD_CONFIG}'::jsonb,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        "updated_at" timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT "PK_bo_companies_id" PRIMARY KEY ("id")
      )
    `)
    await queryRunner.query(`
      INSERT INTO "bo"."companies" ("id", "name", "theme")
      VALUES (1, 'Desenvolvimento', 'default')
      ON CONFLICT ("id") DO NOTHING
    `)
    await queryRunner.query(`
      SELECT setval(
        pg_get_serial_sequence('"bo"."companies"', 'id'),
        GREATEST((SELECT COALESCE(MAX("id"), 1) FROM "bo"."companies"), 1)
      )
    `)
    await queryRunner.query(
      `ALTER TABLE "bo"."companies" ADD COLUMN IF NOT EXISTS "whatsapp_number" varchar(40)`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."companies" ADD COLUMN IF NOT EXISTS "dashboard_config" jsonb`,
    )
    await queryRunner.query(
      `UPDATE "bo"."companies" SET "dashboard_config" = '${DEFAULT_DASHBOARD_CONFIG}'::jsonb WHERE "dashboard_config" IS NULL`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."companies" ALTER COLUMN "dashboard_config" SET DEFAULT '${DEFAULT_DASHBOARD_CONFIG}'::jsonb`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."companies" ALTER COLUMN "dashboard_config" SET NOT NULL`,
    )
    await queryRunner.query(
      `CREATE UNIQUE INDEX IF NOT EXISTS "UQ_bo_companies_whatsapp_number" ON "bo"."companies" ("whatsapp_number") WHERE "whatsapp_number" IS NOT NULL`,
    )

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "bo"."users" (
        "id" uuid NOT NULL DEFAULT gen_random_uuid(),
        "name" varchar(255) NOT NULL,
        "username" varchar(100) NOT NULL,
        "email" varchar(255),
        "password" varchar(255) NOT NULL,
        "company_id" integer NOT NULL DEFAULT 1,
        "root" boolean NOT NULL DEFAULT false,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        "updated_at" timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT "PK_bo_users_id" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_bo_users_username" UNIQUE ("username"),
        CONSTRAINT "UQ_bo_users_email" UNIQUE ("email")
      )
    `)
    await queryRunner.query(
      `ALTER TABLE "bo"."users" ADD COLUMN IF NOT EXISTS "company_id" integer`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."users" ADD COLUMN IF NOT EXISTS "root" boolean NOT NULL DEFAULT false`,
    )
    await queryRunner.query(`
      DO $$
      DECLARE
        unresolved_users integer;
        company_count integer;
      BEGIN
        SELECT count(*) INTO unresolved_users FROM "bo"."users" WHERE "company_id" IS NULL;
        SELECT count(*) INTO company_count FROM "bo"."companies";
        IF unresolved_users > 0 AND company_count > 1 THEN
          RAISE EXCEPTION 'Há usuários sem empresa e mais de uma empresa cadastrada. Associe os usuários antes de executar esta migration.';
        END IF;
        UPDATE "bo"."users"
        SET "company_id" = (SELECT "id" FROM "bo"."companies" ORDER BY "id" LIMIT 1)
        WHERE "company_id" IS NULL;
      END $$
    `)
    await queryRunner.query(`ALTER TABLE "bo"."users" ALTER COLUMN "company_id" SET NOT NULL`)
    await queryRunner.query(
      `ALTER TABLE "bo"."users" DROP CONSTRAINT IF EXISTS "FK_bo_users_company_id"`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."users" ADD CONSTRAINT "FK_bo_users_company_id" FOREIGN KEY ("company_id") REFERENCES "bo"."companies"("id") ON DELETE RESTRICT`,
    )
    await queryRunner.query(
      `CREATE INDEX IF NOT EXISTS "IDX_bo_users_company_id" ON "bo"."users" ("company_id")`,
    )
    await queryRunner.query(`
      DO $$
      BEGIN
        IF EXISTS (
          SELECT 1 FROM "bo"."users"
          GROUP BY lower("username") HAVING count(*) > 1
        ) THEN
          RAISE EXCEPTION 'Há usuários com nomes duplicados sem diferenciar maiúsculas de minúsculas. Normalize os usernames antes de executar esta migration.';
        END IF;
      END $$
    `)
    await queryRunner.query(
      `CREATE UNIQUE INDEX IF NOT EXISTS "UQ_bo_users_username_lower" ON "bo"."users" (lower("username"))`,
    )

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "bo"."clients" (
        "id" uuid NOT NULL DEFAULT gen_random_uuid(),
        "name" varchar(255) NOT NULL,
        "email" varchar(255),
        "phone" varchar(40),
        "company_id" integer NOT NULL DEFAULT 1,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        "updated_at" timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT "PK_bo_clients_id" PRIMARY KEY ("id")
      )
    `)
    await queryRunner.query(
      `ALTER TABLE "bo"."clients" ADD COLUMN IF NOT EXISTS "company_id" integer`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."clients" ADD COLUMN IF NOT EXISTS "email" varchar(255)`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."clients" ADD COLUMN IF NOT EXISTS "phone" varchar(40)`,
    )
    await queryRunner.query(`
      DO $$
      DECLARE
        unresolved_clients integer;
        company_count integer;
      BEGIN
        SELECT count(*) INTO unresolved_clients FROM "bo"."clients" WHERE "company_id" IS NULL;
        SELECT count(*) INTO company_count FROM "bo"."companies";
        IF unresolved_clients > 0 AND company_count > 1 THEN
          RAISE EXCEPTION 'Há clientes sem empresa e mais de uma empresa cadastrada. Associe os clientes antes de executar esta migration.';
        END IF;
        UPDATE "bo"."clients"
        SET "company_id" = (SELECT "id" FROM "bo"."companies" ORDER BY "id" LIMIT 1)
        WHERE "company_id" IS NULL;
      END $$
    `)
    await queryRunner.query(`ALTER TABLE "bo"."clients" ALTER COLUMN "company_id" SET NOT NULL`)
    await queryRunner.query(
      `ALTER TABLE "bo"."clients" DROP CONSTRAINT IF EXISTS "FK_bo_clients_company_id"`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."clients" ADD CONSTRAINT "FK_bo_clients_company_id" FOREIGN KEY ("company_id") REFERENCES "bo"."companies"("id") ON DELETE RESTRICT`,
    )
    await queryRunner.query(
      `CREATE INDEX IF NOT EXISTS "IDX_bo_clients_company_id" ON "bo"."clients" ("company_id")`,
    )

    await queryRunner.query(`DROP TABLE IF EXISTS "bo"."lead_recommendations"`)
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "bo"."leads" (
        "id" uuid NOT NULL DEFAULT gen_random_uuid(),
        "company_id" integer NOT NULL DEFAULT 1,
        "client_id" uuid,
        "phone" text NOT NULL,
        "email" text,
        "name" text,
        "source_channel" text NOT NULL DEFAULT 'other',
        "legal_area" text,
        "service_type" text,
        "case_summary" text,
        "jurisdiction" text,
        "urgency" text,
        "deadline" text,
        "fee_budget" numeric(12,2),
        "payment_capacity" text,
        "document_readiness" text,
        "requested_human_help" boolean NOT NULL DEFAULT false,
        "qualification_score" integer NOT NULL DEFAULT 0,
        "qualification_level" text NOT NULL DEFAULT 'frio',
        "conversation_status" text NOT NULL DEFAULT 'bot_active',
        "sales_stage" text NOT NULL DEFAULT 'new',
        "interview_at" timestamptz,
        "rehydrate_at" timestamptz,
        "last_message" text,
        "last_message_at" timestamptz,
        "profile" jsonb NOT NULL DEFAULT '{}'::jsonb,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        "updated_at" timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT "PK_bo_leads_id" PRIMARY KEY ("id")
      )
    `)
    await queryRunner.query(
      `ALTER TABLE "bo"."leads" ADD COLUMN IF NOT EXISTS "company_id" integer`,
    )
    await queryRunner.query(`ALTER TABLE "bo"."leads" ADD COLUMN IF NOT EXISTS "client_id" uuid`)
    await queryRunner.query(`ALTER TABLE "bo"."leads" ADD COLUMN IF NOT EXISTS "email" text`)
    await queryRunner.query(
      `ALTER TABLE "bo"."leads" ADD COLUMN IF NOT EXISTS "source_channel" text NOT NULL DEFAULT 'other'`,
    )
    await queryRunner.query(`ALTER TABLE "bo"."leads" ADD COLUMN IF NOT EXISTS "legal_area" text`)
    await queryRunner.query(`ALTER TABLE "bo"."leads" ADD COLUMN IF NOT EXISTS "service_type" text`)
    await queryRunner.query(`ALTER TABLE "bo"."leads" ADD COLUMN IF NOT EXISTS "case_summary" text`)
    await queryRunner.query(`ALTER TABLE "bo"."leads" ADD COLUMN IF NOT EXISTS "jurisdiction" text`)
    await queryRunner.query(`ALTER TABLE "bo"."leads" ADD COLUMN IF NOT EXISTS "urgency" text`)
    await queryRunner.query(`ALTER TABLE "bo"."leads" ADD COLUMN IF NOT EXISTS "deadline" text`)
    await queryRunner.query(
      `ALTER TABLE "bo"."leads" ADD COLUMN IF NOT EXISTS "fee_budget" numeric(12,2)`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."leads" ADD COLUMN IF NOT EXISTS "payment_capacity" text`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."leads" ADD COLUMN IF NOT EXISTS "document_readiness" text`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."leads" ADD COLUMN IF NOT EXISTS "qualification_score" integer NOT NULL DEFAULT 0`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."leads" ADD COLUMN IF NOT EXISTS "qualification_level" text NOT NULL DEFAULT 'frio'`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."leads" ADD COLUMN IF NOT EXISTS "conversation_status" text NOT NULL DEFAULT 'bot_active'`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."leads" ADD COLUMN IF NOT EXISTS "sales_stage" text NOT NULL DEFAULT 'new'`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."leads" ADD COLUMN IF NOT EXISTS "interview_at" timestamptz`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."leads" ADD COLUMN IF NOT EXISTS "rehydrate_at" timestamptz`,
    )
    await queryRunner.query(`
      DO $$
      DECLARE
        unresolved_leads integer;
        company_count integer;
      BEGIN
        SELECT count(*) INTO unresolved_leads FROM "bo"."leads" WHERE "company_id" IS NULL;
        SELECT count(*) INTO company_count FROM "bo"."companies";
        IF unresolved_leads > 0 AND company_count > 1 THEN
          RAISE EXCEPTION 'Há leads globais sem empresa e mais de uma empresa cadastrada. Associe os leads antes de executar esta migration.';
        END IF;
        UPDATE "bo"."leads"
        SET "company_id" = (SELECT "id" FROM "bo"."companies" ORDER BY "id" LIMIT 1)
        WHERE "company_id" IS NULL;
      END $$
    `)
    await queryRunner.query(`ALTER TABLE "bo"."leads" ALTER COLUMN "company_id" SET NOT NULL`)
    await queryRunner.query(`
      DO $$
      BEGIN
        IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'bo' AND table_name = 'leads' AND column_name = 'engagement_score') THEN
          EXECUTE 'UPDATE "bo"."leads" SET "conversation_status" = CASE WHEN "status" IN (''bot_active'', ''awaiting_human'', ''human_active'') THEN "status" ELSE ''bot_active'' END';
        END IF;
      END $$
    `)
    await queryRunner.query(
      `ALTER TABLE "bo"."leads" DROP CONSTRAINT IF EXISTS "UQ_bo_leads_phone"`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."leads" DROP CONSTRAINT IF EXISTS "CK_bo_leads_level"`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."leads" DROP CONSTRAINT IF EXISTS "CK_bo_leads_status"`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."leads" DROP CONSTRAINT IF EXISTS "CK_bo_leads_score"`,
    )
    for (const column of [
      'approximate_age',
      'financial_situation',
      'budget',
      'down_payment',
      'desired_region',
      'property_type',
      'family_size',
      'bedrooms',
      'purchase_timeline',
      'restrictions',
      'interested_in_recommendations',
      'engagement_score',
      'engagement_level',
      'status',
    ]) {
      await queryRunner.query(`ALTER TABLE "bo"."leads" DROP COLUMN IF EXISTS "${column}"`)
    }
    await queryRunner.query(
      `ALTER TABLE "bo"."leads" DROP CONSTRAINT IF EXISTS "FK_bo_leads_company_id"`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."leads" ADD CONSTRAINT "FK_bo_leads_company_id" FOREIGN KEY ("company_id") REFERENCES "bo"."companies"("id") ON DELETE RESTRICT`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."leads" DROP CONSTRAINT IF EXISTS "FK_bo_leads_client_id"`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."leads" ADD CONSTRAINT "FK_bo_leads_client_id" FOREIGN KEY ("client_id") REFERENCES "bo"."clients"("id") ON DELETE SET NULL`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."leads" DROP CONSTRAINT IF EXISTS "CK_bo_leads_source_channel"`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."leads" ADD CONSTRAINT "CK_bo_leads_source_channel" CHECK ("source_channel" IN ('partners', 'lives', 'referrals', 'website', 'other'))`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."leads" DROP CONSTRAINT IF EXISTS "CK_bo_leads_urgency"`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."leads" ADD CONSTRAINT "CK_bo_leads_urgency" CHECK ("urgency" IS NULL OR "urgency" IN ('low', 'medium', 'high'))`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."leads" DROP CONSTRAINT IF EXISTS "CK_bo_leads_qualification_level"`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."leads" ADD CONSTRAINT "CK_bo_leads_qualification_level" CHECK ("qualification_level" IN ('frio', 'morno', 'quente'))`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."leads" DROP CONSTRAINT IF EXISTS "CK_bo_leads_qualification_score"`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."leads" ADD CONSTRAINT "CK_bo_leads_qualification_score" CHECK ("qualification_score" BETWEEN 0 AND 100)`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."leads" DROP CONSTRAINT IF EXISTS "CK_bo_leads_conversation_status"`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."leads" ADD CONSTRAINT "CK_bo_leads_conversation_status" CHECK ("conversation_status" IN ('bot_active', 'awaiting_human', 'human_active'))`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."leads" DROP CONSTRAINT IF EXISTS "CK_bo_leads_sales_stage"`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."leads" ADD CONSTRAINT "CK_bo_leads_sales_stage" CHECK ("sales_stage" IN ('new', 'interview_scheduled', 'interview_completed', 'nurturing', 'contracted', 'lost'))`,
    )
    await queryRunner.query(
      `CREATE UNIQUE INDEX IF NOT EXISTS "UQ_bo_leads_company_phone" ON "bo"."leads" ("company_id", "phone")`,
    )
    await queryRunner.query(`DROP INDEX IF EXISTS "bo"."IDX_bo_leads_activity"`)
    await queryRunner.query(
      `CREATE INDEX IF NOT EXISTS "IDX_bo_leads_activity" ON "bo"."leads" ("company_id", "last_message_at" DESC NULLS LAST, "created_at" DESC)`,
    )
    await queryRunner.query(
      `CREATE INDEX IF NOT EXISTS "IDX_bo_leads_sales_stage" ON "bo"."leads" ("company_id", "sales_stage")`,
    )

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "bo"."lead_messages" (
        "id" uuid NOT NULL DEFAULT gen_random_uuid(),
        "lead_id" uuid NOT NULL,
        "direction" text NOT NULL,
        "sender_type" text NOT NULL,
        "twilio_message_sid" text,
        "in_reply_to_message_id" uuid,
        "message_type" text NOT NULL DEFAULT 'text',
        "processing_status" text NOT NULL DEFAULT 'ready',
        "bot_processing_started_at" timestamptz,
        "bot_processed_at" timestamptz,
        "source_content_type" text,
        "content" text NOT NULL,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT "PK_bo_lead_messages_id" PRIMARY KEY ("id"),
        CONSTRAINT "FK_bo_lead_messages_lead" FOREIGN KEY ("lead_id") REFERENCES "bo"."leads"("id") ON DELETE CASCADE,
        CONSTRAINT "FK_bo_lead_messages_reply" FOREIGN KEY ("in_reply_to_message_id") REFERENCES "bo"."lead_messages"("id") ON DELETE SET NULL
      )
    `)
    await queryRunner.query(
      `CREATE INDEX IF NOT EXISTS "IDX_bo_lead_messages_history" ON "bo"."lead_messages" ("lead_id", "created_at", "id")`,
    )
    await queryRunner.query(
      `CREATE UNIQUE INDEX IF NOT EXISTS "UQ_bo_lead_messages_twilio_sid" ON "bo"."lead_messages" ("twilio_message_sid") WHERE "twilio_message_sid" IS NOT NULL`,
    )
    await queryRunner.query(
      `CREATE UNIQUE INDEX IF NOT EXISTS "UQ_bo_lead_messages_bot_reply" ON "bo"."lead_messages" ("in_reply_to_message_id") WHERE "in_reply_to_message_id" IS NOT NULL AND "sender_type" = 'bot'`,
    )

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "bo"."lead_audio_processing" (
        "id" uuid NOT NULL DEFAULT gen_random_uuid(),
        "message_id" uuid NOT NULL,
        "twilio_media_sid" text NOT NULL,
        "whatsapp_from" text,
        "content_type" text NOT NULL,
        "byte_size" bigint,
        "duration_seconds" numeric,
        "transcription_provider" text,
        "transcription_model" text,
        "language" text,
        "attempt_count" integer NOT NULL DEFAULT 0,
        "next_attempt_at" timestamptz DEFAULT now(),
        "last_error_code" text,
        "last_error_message" text,
        "twilio_media_deleted_at" timestamptz,
        "transcribed_at" timestamptz,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        "updated_at" timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT "PK_bo_lead_audio_id" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_bo_lead_audio_message" UNIQUE ("message_id"),
        CONSTRAINT "UQ_bo_lead_audio_media" UNIQUE ("twilio_media_sid"),
        CONSTRAINT "FK_bo_lead_audio_message" FOREIGN KEY ("message_id") REFERENCES "bo"."lead_messages"("id") ON DELETE CASCADE
      )
    `)
    await queryRunner.query(
      `CREATE INDEX IF NOT EXISTS "IDX_bo_lead_audio_queue" ON "bo"."lead_audio_processing" ("next_attempt_at", "created_at") WHERE "transcribed_at" IS NULL AND "next_attempt_at" IS NOT NULL`,
    )

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "bo"."legal_cases" (
        "id" uuid NOT NULL DEFAULT gen_random_uuid(),
        "company_id" integer NOT NULL,
        "client_id" uuid NOT NULL,
        "lead_id" uuid,
        "title" varchar(255) NOT NULL,
        "service_type" text NOT NULL,
        "description" text,
        "contracted_fee" numeric(12,2) NOT NULL,
        "stage" text NOT NULL DEFAULT 'awaiting_initial_payment',
        "documents_complete" boolean NOT NULL DEFAULT false,
        "contract_signed_at" timestamptz NOT NULL,
        "started_at" timestamptz,
        "completed_at" timestamptz,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        "updated_at" timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT "PK_bo_legal_cases_id" PRIMARY KEY ("id"),
        CONSTRAINT "FK_bo_legal_cases_company" FOREIGN KEY ("company_id") REFERENCES "bo"."companies"("id") ON DELETE RESTRICT,
        CONSTRAINT "FK_bo_legal_cases_client" FOREIGN KEY ("client_id") REFERENCES "bo"."clients"("id") ON DELETE RESTRICT,
        CONSTRAINT "FK_bo_legal_cases_lead" FOREIGN KEY ("lead_id") REFERENCES "bo"."leads"("id") ON DELETE SET NULL
      )
    `)
    await queryRunner.query(
      `CREATE UNIQUE INDEX IF NOT EXISTS "UQ_bo_legal_cases_lead" ON "bo"."legal_cases" ("lead_id") WHERE "lead_id" IS NOT NULL`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."legal_cases" DROP CONSTRAINT IF EXISTS "CK_bo_legal_cases_stage"`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."legal_cases" ADD CONSTRAINT "CK_bo_legal_cases_stage" CHECK ("stage" IN ('awaiting_initial_payment', 'document_collection', 'public_services_scheduling', 'diligences', 'awaiting_documents', 'final_artifacts', 'client_final_delivery', 'awaiting_final_payment', 'closed'))`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."legal_cases" DROP CONSTRAINT IF EXISTS "CK_bo_legal_cases_fee"`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."legal_cases" ADD CONSTRAINT "CK_bo_legal_cases_fee" CHECK ("contracted_fee" > 0)`,
    )
    await queryRunner.query(
      `CREATE INDEX IF NOT EXISTS "IDX_bo_legal_cases_company_stage" ON "bo"."legal_cases" ("company_id", "stage")`,
    )
    await queryRunner.query(
      `CREATE INDEX IF NOT EXISTS "IDX_bo_legal_cases_client" ON "bo"."legal_cases" ("client_id")`,
    )

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "bo"."invoices" (
        "id" uuid NOT NULL DEFAULT gen_random_uuid(),
        "legal_case_id" uuid NOT NULL,
        "kind" text NOT NULL,
        "percentage" numeric(5,2) NOT NULL,
        "amount" numeric(12,2) NOT NULL,
        "status" text NOT NULL DEFAULT 'requested',
        "due_at" timestamptz,
        "issued_at" timestamptz,
        "paid_at" timestamptz,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        "updated_at" timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT "PK_bo_invoices_id" PRIMARY KEY ("id"),
        CONSTRAINT "FK_bo_invoices_case" FOREIGN KEY ("legal_case_id") REFERENCES "bo"."legal_cases"("id") ON DELETE CASCADE,
        CONSTRAINT "UQ_bo_invoices_case_kind" UNIQUE ("legal_case_id", "kind")
      )
    `)
    await queryRunner.query(
      `ALTER TABLE "bo"."invoices" DROP CONSTRAINT IF EXISTS "CK_bo_invoices_kind"`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."invoices" ADD CONSTRAINT "CK_bo_invoices_kind" CHECK ("kind" IN ('partial', 'final'))`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."invoices" DROP CONSTRAINT IF EXISTS "CK_bo_invoices_status"`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."invoices" ADD CONSTRAINT "CK_bo_invoices_status" CHECK ("status" IN ('requested', 'issued', 'paid'))`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."invoices" DROP CONSTRAINT IF EXISTS "CK_bo_invoices_values"`,
    )
    await queryRunner.query(
      `ALTER TABLE "bo"."invoices" ADD CONSTRAINT "CK_bo_invoices_values" CHECK ("amount" >= 0 AND (("kind" = 'partial' AND "percentage" = 30) OR ("kind" = 'final' AND "percentage" = 70)))`,
    )
    await queryRunner.query(
      `CREATE INDEX IF NOT EXISTS "IDX_bo_invoices_status" ON "bo"."invoices" ("status")`,
    )

    await queryRunner.query(`DROP TABLE IF EXISTS "bo"."dossier_properties"`)
    await queryRunner.query(`DROP TABLE IF EXISTS "bo"."dossier_clients"`)
    await queryRunner.query(`DROP TABLE IF EXISTS "bo"."dossiers"`)
    await queryRunner.query(`DROP TABLE IF EXISTS "bo"."company_api_tokens"`)
  }

  public async down(): Promise<void> {
    throw new Error(
      'CreateLegalBackoffice é irreversível: restaure um backup para voltar ao domínio anterior.',
    )
  }
}
